- hakjin/1000_aplusb.c
- hakjin/10171_고양이.c
- hakjin/1292_쉽게푸는문제.c
- hakjin/14469_whycow.c
/*
A+B의 알고리즘 분류는 수학, 단순 구현입니다.
고양이의 알고리즘 분류는 단순 구현입니다.
제목에 고양이가 들어있어서 한 번 풀어보았습니다.
*/
1292번의 알고리즘 분류는 수학, 구현입니다.
진짜 쉽게 풀릴까 싶어서 풀어봤는데 다행히 쉬웠네요ㅎㅎ
이중 for문을 써서 시간초과가 나지 않을까 걱정했는데 다행이 전체 크기가 1000이하로 제한되어있어서 괜찮았습니다.
14469번의 알고리즘 분류는 그리디알고리즘, 정렬입니다.
도착한 순서에 따라 정렬만 해주니 쉽게 풀렸습니다.
> hakjin / 3_4 / 2문제

- daehee/10974.cpp
- daehee/14719.cpp
- daehee/9184.cpp
모든 수열의 알고리즘 분류는 브루트포스 알고리즘, 백트래킹입니다.
신나는 함수 실행의 알고리즘 분류는 다이나믹 프로그래밍, 재귀입니다.
빗물의 알고리즘 분류는 구현, 시뮬레이션입니다.
> daehee / 3_4 / 3문제

- shkisme/2557.cpp
- shkisme/C++ 복습/1_10818.cpp
- shkisme/C++ 복습/2_11931.cpp
- shkisme/C++ 복습/3_10809.cpp
- shkisme/C++ 복습/4_1764.cpp
- shkisme/다이나믹 프로그래밍/1_1463.cpp
> shkisme / 3_4 / 1문제

- HyeonWoo/1003_pibonacci.cpp
- HyeonWoo/1011_FlymetotheAlphaCentauri.cpp
피보나치 함수의 알고리즘 분류는 다이나믹 프로그래밍입니다.
Fly me to the Alpha Centauri의 알고리즘 분류는 수학입니다.
Fly me to the Alpha Centauri의 테스트 케이스 범위가 생각보다 넓어서 자료형 범위 문제 때문에 시간을 많이 뺏긴 것 같습니다.
> HyeonWoo / 3_4 / 2문제

- 202155558/1357.c
https://www.acmicpc.net/problem/1357
알고리즘 분류는 수학 단순구현입니다
> 창완/3_4/1문제

- yoonsung/1966_프린터큐.cpp
- yoonsung/2108_통계학.cpp
2108의 알고리즘 : 수학, 구현, 정렬
산술평균을 출력할 때 자료형을 올바르게 사용하지 않아 시간이 걸렸습니다.
1966의 알고리즘 : 구현, 큐
효율적인 프로그램이 되도록 생각하는 것이 어려웠습니다
> yoonsung / 3_4 / 2문제

- dib3474/1546_평균.c
- dib3474/4344_평균은 넘겠지.c
1556_평균, 4344_평균은 넘겠지의 알고리즘 분류는 수학입니다.
4344_평균은 넘겠지의 마지막 출력에서 형변환을 잘못해서 시간이 오래 걸렸습니다.
> dib3474 / 3_4 / 2문제

- ichanguk/1149_RPG거리.cpp
- ichanguk/1309_동물원.cpp
https://www.acmicpc.net/problem/1149
다이나믹 프로그래밍입니다.
i차례에서 R로 칠할 때, G로 칠할 때, B로 칠할 때 각각의 최소비용을 전단계까지의 최소비용에 계속 더하며 구하는 문제인데
다이나믹 프로그래밍이란걸 처음해봐서 구글링으로 다이나믹 프로그래밍이 뭔지 찾아보고 해봤습니다.
https://www.acmicpc.net/problem/1309
이 문제도 다이나믹 프로그래밍입니다.
비슷한 문제인데 2차원 배열 크기가 클 땐 전역변수로 선언해야 되는 걸 새로 배웠네요..
> changuk / 3_4 / 2문제

- yejin/1065_한수.cpp
- yejin/1110_더하기사이클.cpp
'더하기 사이클'의 알고리즘 분류는 수학, 구현입니다.
'한수'의 알고리즘 분류는 브루트포스 알고리즘입니다.
이번에 처음 해보는거라 두 문제 다 평균보다 시간이 조금씩은 더 걸린 것 같습니다.
적당한 변수 이름 정하는게 생각보다 어렵네요..!
> yejin / 3_4 / 2문제

- NamWoeunJung/1912_continuousSum.cpp
- NamWoeunJung/1912_continuousSumFail.cpp
- NamWoeunJung/9251_LCS.cpp
[BOJ]  9251번 - LCS
알고리즘 분류: 다이나믹 프로그래밍
요즘 DP를 공부하고 있어서 가장 기본적인 문제인 LCS 문제를 풀어봤습니다! DP의 문제풀이 단계에 따라 초기 조건(Base condition)을 정하고 동적계획 공식(같은 문자열이면 LCS[i-1][j-1]+1, 다르면 LCS[i][j-1],LCS[i-1][j] 중 큰 것) 에 따라 문제를 풀었습니다!
초기조건에 i=0이거나 j=0일 때 0으로 넣고 까먹어서 문자열 비교를 할 때 str[i] == str[j]라고 적어서 오류가 나서 시간이 조금 걸렸습니다!! 마찬가지의 이유로 dp의 배열크기를 처음에 1000,1000으로 했다가 RunTime Error - out of bound 오류가 나서 1001,1001로 수정해주었습니다!!
[BOJ]  1912번 - 연속합
알고리즘 분류: 다이나믹 프로그래밍
처음엔 dp를 이용하는 문제라고 해서 n*n 배열을 만들어서 동적 할당을 통해 문제를 풀었습니다. 하지만 받아오는 배열의 크기가 최대 10^5개이므로 너무 커져서 메모리 초과 오류가 떴습니다. 이를 해결하기 위해 이차원 배열 대신 일차원 배열을 만들어서 더했을때 값이 커지면 dp의 값을 바꾸도록 수정하였습니다.
> NamWoeunJung / 3_4 / 2문제

- sososo0/1065_한수.cpp
- sososo0/1978_소수찾기.cpp
한수의 알고리즘 분류는 함수 구현입니다.
소수 찾기의 알고리즘 분류는 기본 수학 입니다.
> 박소현/3_4/2문제

- Nocha12/17485_진우의 달 여행 (Large).cpp
- Nocha12/9625_BABBA.cpp
BABBA 문제는 DP 이며, 점화식을 세워 풀었습니다.
진우의 달 여행 문제는 DP 이며, 이 또한 점화식을 세웠습니다.
이 문제의 경우 바로 위의 라인만 비교하는 실수를 저질러 문제 해결 시간이 늘었고,
dp 테이블을 초기화 할때, 기본값을 안일하게 999 로 줘버리는 바람에 해결시간이 길어졌습니다.
> 양준석 / 3_4 / 2문제

- PEJ12/10773_제로.C++
- PEJ12/11047_동전 0.C++
동전0의 알고리즘 분류는 그리디 알고리즘입니다. 
17번째 줄에서 =을 빼고 적어서 오류 찾는데 시간이 쫌 걸린 게 힘든 부분 이였습니다.
> PEJ12 / 3_4/ 2문제

- Yeonghun/1037_divisor.c
- Yeonghun/1059_GoodSection.c
약수 구하기 문제는 어떤 수 N의 모든 약수가 주어졌을 때 그 모든 약수를 가지는 수 N을 구하는 문제입니다.
구현하는 것 자체는 그렇게 어렵지 않았는데, 주어진 수를 약수로 가지기 때문에 주어진 수보다 무조건 커야한다는 점을 간과해서 계속 오류가 났습니다.
(가령 2랑 4가 주어지면 4도 2랑 4를 약수로 가지지만 주어진 수랑 같으면 안되므로 8을 출력하는 식)
좋은 구간 문제는 주어진 조건을 만족하는 구간을 몇종류나 만들수 있는지에 대한 문제인데, 구간을 셀 때 한쪽방향으로만 구간이 변하는걸 세어서 틀렸습니다.
> [PGS] 강영훈/3_4/2문제

- taeyune/1004_youngprince.py
- taeyune/1913_snail.py
- taeyune/DRAWRECT.py
- taeyune/FESTIVAL.py
1. [BOJ] 1913_달팽이
snail 문제를 재귀적으로 풀어보았습니다. 
재귀함수 구상하는 부분이 어려웠습니다. (A4에 그려가면서 품) 
2. [BOJ] 1004_어린왕자
수학/기하학 기초 문제. 
3. [Algospot] FESTIVAL
알고리즘해결전략 책 첫 문제-! 조건을 맞춰주기 위해 작성한 for문이 까다로웠다.
4. [Algospot] DRAWRECT
단순구현문제였다.
> taeyune/3_4/4문제 #1

- 안태영/1157_단어공부.py
https://www.acmicpc.net/problem/1157
Sorting
> 안태영/3_4/1문제

- ichanguk/1138_한줄로서기.cpp
- ichanguk/1283_단축키지정.cpp
https://www.acmicpc.net/problem/1138
한 줄로 서기 문제 알고리즘 분류는 구현입니다.
인원 수, 키 순으로 줄에서 자기보다 키 큰 사람이 앞에 몇 명이 있었는지를 입력하면 한 줄로 줄을 세워주는 프로그램입니다. 0으로 초기화된 배열에 순서대로 자리를 채워나가는 방식으로 만들었습니다.
https://www.acmicpc.net/problem/1283
단축키 지정 문제 알고리즘 분류는 구현, 문자열입니다.
N개의 문장을입력받고 첫 글자가 처음 나온거라면 그 글자에 대괄호를 씌워서 출력합니다.
글자가 처음 나온 게 아니라면 다음 단어들의 첫글자들, 또 아니라면 첨부터 쭉 돌면서 처음 나온 문자가 있으면 대괄호, 없으면 그냥 출력하는 문제입니다.
예시보고 문장 첫 글자들은 다 대문자로 입력받는 줄 알았는데 그냥 대소문자 구분 없는 문제였어서 몇 번 틀리고 좀 수정했습니다.
> changuk / 4_1 / 2문제

- NamWoeunJung/11047_coin0.cpp
- NamWoeunJung/1931_meetingRoomAssignment.cpp
[BOJ] 11047번 - 코인0
알고리즘 분류: 그리디 알고리즘
큰 가격부터 비교해가며 K보다 작거나 같으면 빼주었습니다.
주어지는 가격이 서로의 배수이기 때문에 그리디로 쉽게 풀 수 있었습니다.
[BOJ] 1931번 - 회의실 배정
알고리즘 분류: 그리디 알고리즘
처음에 시작시간, 마치는 시간 순으로 정렬하는 걸로 잘못 알아서 오류를 수정하느라 시간이 조금 걸렸습니다.
> NamWoeunjung / 4_4 / 2문제

- xcelxlorx/PGS_로또의 최고 순위와 최저 순위
https://programmers.co.kr/learn/courses/30/lessons/77484
> xcelxlorx / 5_1 / 1문제

- daehee/17144.cpp
- daehee/9657.cpp
https://www.acmicpc.net/problem/9657
- 다이나믹 프로그래밍 
- 게임 이론
이산수학에서 다룬 내용을 이용해서 풀어보았습니다.
https://www.acmicpc.net/problem/17144
- 구현
- 시뮬레이션
bool값으로 continue 조건을 설정해서 공기청정기 자리에 들어간 -1을 걸러내지 못해 고생했습니다..
> daehee / 5_1 / 2문제

- HyeonWoo/1002_cabbage.cpp
- HyeonWoo/1013_contact.cpp
유기농 배추의 알고리즘 분류는 dfs입니다.
contact의 알고리즘 분류는 문자열, 정규표현식입니다.
contact의 문자열 패턴 중 시작 지점이 모호한 경우가 있어 살짝 당황했습니다.
> HyeonWoo /  5_1 / 2문제

- sososo0/17609_회문.py
- sososo0/2504_괄호의값.py
괄호의 값의 알고리즘 분류는 구현, stack입니다.
회문의 알고리즘 분류는 단순구현입니다.
파이썬을 배우는 수업시간에 공부한 내용을 가지고 복습을 한다는 생각으로 풀어보았습니다.
> 박소현/5_1/2문제

- PEJ12/1026_보물.c++
- PEJ12/1037_약수.cpp
보물의 알고리즘 분류는 수학, 그리디 알고리즘, 정렬입니다.
약수의 알고리즘 분류는 수학, 정수론 입니다.
> PEJ12 / 5_1 /2문제

- dib3474/17478_재귀함수가_뭔가요.py
- dib3474/2839_설탕 배달.py
재귀, 기본수학
재귀를 잘 안 써봤고, '재귀함수가 뭔가요?' 유형의 재귀는 처음이라 어려웠습니다.
> dib3474 / 5_1 / 2문제

- yoonsung/18111_마인크래프트.cpp
- yoonsung/2630_색종이 만들기.cpp
마인크래프트의 알고리즘 분류는 완전 탐색입니다.
색종이 만들기의 알고리즘 분류는 분할 정복입니다.
> yoonsung / 5_1 / 2문제

- yejin/1193_분수찾기.cpp
- yejin/5635_생일.cpp
분수찾기의 알고리즘 분류는 수학, 구현입니다.
문제에 제시된 표를 잘못보고 푸는 바람에 수정하느라 더 시간이 들어간게 아쉽습니다.
생일의 알고리즘 분류는 구현, 문자열, 정렬입니다.
C++ 수업시간에 클래스 배우고 있어서 사용해봤습니다.
> yejin / 5_1 / 2문제

- dib3474/1157_단어 공부.py
- dib3474/1978_소수 찾기.c
알고리즘 분류 : 수학, 구현, 문자열
최근 소수와 관련된 내용을 배워서 엄청 많이 어렵지 않았습니다.
> dib3474 / 5_2 / 2문제

- ichanguk/1213_팰린드롬 만들기.cpp
- ichanguk/1535_안녕.cpp
팰린드롬 만들기 알고리즘 분류는 구현, 문자열, 그리디 알고리즘입니다.
문자열이 팰린드롬인지 팰린드롬이 아닌지를 구현하는 것은 익숙한데 팰린드롬이 아닌 문자열을 받아서 팰린드롬을 만드는 것은 처음 해봐서 조금 이해하는데 시간이 걸렸습니다.
입력으로 받은 문자들을 사전순으로 정렬한 후 홀수개인 문자가 2개 이상이면 팰린드롬을 만들 수 없기 때문에 먼저 그 부분을 생각해주고 홀수인 문자가 1개 있으면 그 문자를 문자열의 끝에 놔주고 나머지 문자들은 다 앞으로 당겨온 다음 문자열의 처음과 끝을 오가며 팰린드롬을 완성해갑니다. 처음과 끝을 오가는 반복문을 작성하면 문자열에 끝에 놔덨던 홀수 문자가 가운데로 오도록 할 수 있습니다.
안녕 문제 알고리즘 분류는 다이나믹 프로그래밍, 브루트포스 알고리즘입니다.
모든 경우의 수를 다이나믹 프로그래밍으로 찾아가는 문제입니다. 제한된 체력 안에서 가장 많은 기쁨을 얻을 수 있는 경우의 값을 구하는 건데 j체력을 소모했을 때 얻을 수 있는 기쁨을 DP[i][j]에 저장하며 모든 경우의 수를 계산합니다.
> ichanguk / 5_2 / 2문제

- ichanguk/5600_품질검사.cpp
- ichanguk/9095_1,2,3 더하기.cpp
1,2,3 더하기 문제의 알고리즘 분류는 다이나믹 프로그래밍입니다.
점화식을 이용해서 풀 수 있는 문제입니다.
4를 1,2,3의 합으로 만드는 경우의 수는 1을 만드는 경우에 3을 더해주거나 2를 만드는 경우에 2를 더해주거나 3을 만드는 경우에 1을 더해주면 만들 수 있으므로 1을 만드는 경우의 수 + 2를 만드는 경우의 수 + 3을 만드는 경우의 수로 구할 수 있고
DP[n] = DP[n-1] + DP[n-2] + DP[n-3] (이때, n>=4)  이러한 점화식을 구해서 구현했습니다.
품질검사 문제의 알고리즘 분류는 구현입니다.
입력을 모두 저장한 다음 고장났다고 검사했던 3부품 중 나머지 2부품이 정상이라면 남은 1부품은 고장난 것으로 확정지어주고 출력하는 프로그램입니다. 입력을 받음과 동시에 뭘 하려고 하기보단 입력을 다 받은 다음 다시 살펴봐야하는 문제입니다.
> ichanguk / 5_3 / 2문제

- sososo0/11729_하노이 탑 이동순서.py
- sososo0/2448_별 찍기 - 11.py
하노이 탑 이동 순서의 알고리즘 분류는 재귀함수 사용, 단순 구현 입니다.
별 찍기 - 11의 알고리즘 분류는 재귀함수 사용, 단순 구현 입니다.
수업시간에 배운 내용을 가지고 복습을 하는 차원에서 문제를 선정해보았습니다.
> sososo0 / 5_3 / 2문제

- yoonsung yang/7662_이중 우선순위 큐.cpp
-이중 우선 순위 큐-
우선순위 큐
우선순위 큐 2개를 사용하여 하나는 큰 값을 다른 하나는 작은 값을 삭제하는 역할을 하도록 하고, 맵을 사용하여 중복된 값을 삭제 할 수 있도록 구현 했습니다. 
방법을 생각하는 것은 오래 걸리지 않았지만 구현을 하는 과정에서 예외 처리를 잘 하지 못해 시간이 오래 걸렸습니다.
> yoonsung yang / 5_3 / 1문제

- ichanguk/1680_쓰레기 수거
- ichanguk/1748_수 이어 쓰기1
쓰레기 수거 문제 알고리즘 분류는 구현, 시뮬레이션입니다.
쓰레기차 용량을 생각하면서 용량이 넘치면 다시 쓰레기장에 가서 쓰레기차를 비우고 오고 아니면 쓰레기를 싣고 가는 과정을 반복하다가 끝나면 쓰레기장으로 복귀하는 과정을 구현하는 문제이고 어렵지 않았습니다.
수 이어 쓰기 1 문제 알고리즘 분류는 수학, 구현입니다.
if문을 많이 써서 풀면 쉽게 풀 수 있으나 시간복잡도가 크기 때문에 입력 받은 수의 자릿수를 이용해 한 번에 계산 가능한 부분은 바로 계산해서 최대한 시간 복잡도를 줄이는 코드를 짜봤습니다.
> ichanguk / 5_5 / 1문제
